### PR TITLE
Use Deno

### PR DESCRIPTION
**Pull request by vwkd**
This is a demo how the module could look like using Deno based on #3. It's mainly for inspiration. Feel free to close whenever you like.

If of real interest, then spec-url should likely be published first as a Deno module such that it can be imported natively here. Though there are ways to import a node package in Deno via a module CDN like skypack.dev that does the necessary transformations, I don't know what transformations are and are not supported (not everything can be mapped 1-to-1 to Deno, ongoing effort in [std/node](https://deno.land/std/node)). I think in this case it can, but to keep things simple to understand, I just ported spec-url https://github.com/alwinb/spec-url/pull/10 and used it here.

Also there are nicer ways to import in Deno, like using [import maps](https://deno.land/manual@main/npm_nodejs/import_maps) or some `deps.js` file to just maintain URLs in a single place. But I didn't want to complicate the demo any further and left it plain simple here.

Using this in reality would likely mean unpublishing from NPM (and publishing to some Deno registry like deno.land/x). One of the differences with Deno is that it has no package manager and uses full URLs like the browser. An advantage is that therefore any registry is inherently browser compatible because it just offers URLs. For example, when using [deno.land/x](https://deno.land/x) (which is just a simple proxy for GitHub) one would get URLs like `https://deno.land/x/reurl@v1.0.0/lib/index.js` which could just as well be imported in a script tag in the browser. (Of course, the test files are server-specific and won't run in the browser when imported.)

### CODE REVIEW

**Comment by alwinb** [comment]
So, is there a way to turn this into a hybrid, a proper deno module that is at the same time a proper nodejs module on npm? I think making it available as a deno module is a good thing to do, especially if it's not too much work.

**Comment by vwkd** [comment]
I was indeed confused myself. I think it should be possible, since this module is a browser module and doesn't rely on any server runtime APIs. Leaving it on NPM would be just another registry. If you use Node or Deno internally for testing doesn't matter. The confusing part to me was that NPM just clones the whole repo into the `node_modules`, but indeed a user won't usually run reurl's tests.

**Comment by alwinb** [comment]
Hmm so it is a bit messy all, then. Or at least, something that takes some research, to find a nice solution :/

**Comment by vwkd** [comment]
I guess the final answer is that it's not possible to write code that works on both old and new. Either write code that works on old and use a module CDN to use on new. Or write code that works on new but not anymore on old.

I'll close this PR. Feel free to revisit whenever the requirement to support old changes.

**Comment by alwinb** [comment]
Sure! Thanks,

**Pull request closed without merging**
